server:
  port: 8080
  servlet:
    context-path: /api
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,gateway